version: '2'
services:
  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local